### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/mobile-services.en#18]
Issue in help/ios/getting-started/proc-rules.md

The [Processing Rules Training](https://tv.adobe.com/embed/1181/16506/) link on this page is redirected to the Support homepage. Please update with a correct link.

Ref: https://docs.adobe.com/content/help/en/mobile-services/ios/getting-started-ios/proc-rules.html

**Comment by gigazelle** [comment]
Looks like that video was removed, so the link referencing it was removed from the docs too.
